version: '3.4'

services:
  rcms-api:
    image: rcms-api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
